### ISSUE TITLE
MacOS release

### ISSUE THREAD

**Issue by lammel-hub** [Wiselabs/simplexity#2]
If possible, please make MacOs release, as per previous discussion.

**Comment by fronald** [comment]
Yes, is possible. We are already doing it.

Thank you very much for your interest in our project. It will be available soon. We are testing it. Would you be able to test it on macOS ARM?

**Comment by lammel-hub** [comment]
Sorry, only have access to Win and Linux distros. (Suggested MacOS for a broader audience to find the app)

**Comment by fronald** [comment]
Ok. The build for macOS is ready. Universal platform, i can test on x86_64 and is fine. If anyone test on ARM and have any issues, can open a new ticket. Today i'll release the 1.0.1.

**Comment by fronald** [comment]
Done. Please check the 1.0.1 version.

Thanks.
